spring:
  profiles:
    include: dev
  quartz:
    auto-startup: true
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            misfireThreshold: 60000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
          scheduler:
            instanceName: QuartzTestSM
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  type-aliases-package: com.api.quartz.domain
  mapper-locations:
  - classpath:mapper/*.xml
